"""loans_table

Revision ID: f17f54d0e077
Revises: f24f23c21ccd
Create Date: 2024-08-04 00:13:36.976737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f17f54d0e077'
down_revision: Union[str, None] = 'f24f23c21ccd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('loans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('book_replica_id', sa.String(), nullable=False),
    sa.Column('loan_date', sa.DateTime(), nullable=False),
    sa.Column('end_loan_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_replica_id'], ['books_replicas.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_loans_id'), 'loans', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_loans_id'), table_name='loans')
    op.drop_table('loans')
    # ### end Alembic commands ###
